In [1]:
import pandas as pd

# Load dataset
data_path = "output_files/chewychewy_products.json"
df = pd.read_json(data_path)

df.head()

,url,title,description,price,image_url,category
0,https://chewychewy.vn/products/set-back-to-basics,SET BACK TO BASICS,Set 12 bánh với 4 loại nhân kem đặc biệt c...,149000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy
1,https://chewychewy.vn/products/set-mini-chicpo,SET MINI CHICPO,Set 12 bánh với sốt mayonaise được chế biế...,159000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy
2,https://chewychewy.vn/products/set-mini-bingo,SET MINI BINGO,Set 12 bánh mix giữa 6 bánh nhân vanilla và...,179000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy
3,https://chewychewy.vn/products/set-elegant,EVENT CAKE S07,"Set bánh bao gồm 20 bánh, nhân bánh vanill...",519000 VND,http://product.hstatic.net/200000140863/produc...,Bánh Event sinh nhật
4,https://chewychewy.vn/products/event-cake-s06-1,EVENT CAKE S06,* Lưu ý: Bánh sinh nhật thì Chewiers vui l...,429000 VND,http://product.hstatic.net/200000140863/produc...,Bánh Event sinh nhật

In [2]:
import pandas as pd
print(pd.__file__)

D:\Lib\site-packages\pandas\__init__.py

In [3]:
df.columns

Index(['url', 'title', 'description', 'price', 'image_url', 'category'], dtype='str')

In [4]:
df.head()

,url,title,description,price,image_url,category
0,https://chewychewy.vn/products/set-back-to-basics,SET BACK TO BASICS,Set 12 bánh với 4 loại nhân kem đặc biệt c...,149000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy
1,https://chewychewy.vn/products/set-mini-chicpo,SET MINI CHICPO,Set 12 bánh với sốt mayonaise được chế biế...,159000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy
2,https://chewychewy.vn/products/set-mini-bingo,SET MINI BINGO,Set 12 bánh mix giữa 6 bánh nhân vanilla và...,179000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy
3,https://chewychewy.vn/products/set-elegant,EVENT CAKE S07,"Set bánh bao gồm 20 bánh, nhân bánh vanill...",519000 VND,http://product.hstatic.net/200000140863/produc...,Bánh Event sinh nhật
4,https://chewychewy.vn/products/event-cake-s06-1,EVENT CAKE S06,* Lưu ý: Bánh sinh nhật thì Chewiers vui l...,429000 VND,http://product.hstatic.net/200000140863/produc...,Bánh Event sinh nhật

In [5]:
# Lấy toàn bộ giá trị trong cột 'title' dưới dạng list
title_list = df['title'].tolist() # in ra thông tin của cột title chuyển thành dạng list
print(title_list)

['SET BACK TO BASICS', 'SET MINI CHICPO', 'SET MINI BINGO', 'EVENT CAKE S07', 'EVENT CAKE S06', 'EVENT CAKE S05', 'EVENT CAKE S04', 'SET MINI GREENTEA', 'EVENT CAKE E46', 'EVENT CAKE E45', 'EVENT CAKE E44', 'EVENT CAKE E43', 'EVENT CAKE E42', 'EVENT CAKE E41', 'EVENT CAKE E40', 'EVENT CAKE E39', 'EVENT CAKE E38', 'EVENT CAKE E37', 'EVENT CAKE E36', 'EVENT CAKE E35', 'EVENT CAKE E34', 'EVENT CAKE E33', 'EVENT CAKE E32', 'EVENT CAKE E31', 'EVENT CAKE E30', 'EVENT CAKE E25', 'EVENT CAKE E24', 'EVENT CAKE E23', 'EVENT CAKE E22', 'EVENT CAKE E21', 'EVENT CAKE E20', 'ORIGINAL CHICKEN FLOSS', 'SET MINI BLACK PEARL', 'SET MINI CRUSTY', 'YIPPEE CHOCO CRUNCCH', 'NUTTER CHOCO CRUNCH', 'FROOTY CHOCO CRUNCH', 'BLACK PEARL', 'ORANGE VENUS', 'APPLE CHEESE', 'STRAWBERRY CHEESE', 'STRAWBERRY COTTON YOGURT', 'APPLE COTTON YOGURT', 'BLUEBERRY COTTON YOGURT', 'CHEESE LOVER', 'BLUEBERRY CHEESE', 'BLUEBERRY CHEDDARS', 'STRAWBERRY CHEDDARS', 'CHOCOLATE OREO CRUNCH', 'BLUEBERRY ANGEL', 'ALMOND SWEETHEART', 'ALMOND CHOCOLATE CRUNCH', 'GREEN TEA', 'SET MINI DORAEMON', 'CHEWY CHOCOLATE', 'CHEWY ORIGINAL', 'STRAWBERRY DREAM', 'APLLE DELIGHT', 'MANGO DELUXE', 'ORIGINAL PORK FLOSS', 'SET MINI BƠ TỎI', 'SET MINI PORK FLOSS', 'SET MINI HAPPY', 'SET MINI LUXURY', 'SET MINI DELUXE', 'SET MINI CHOCOLATE', 'SET MINI VANILLA', 'SET MINI YOGURT', 'SET MINI MANGO DELUXE', 'SET MINI SPICY CHICKEN', 'EVENT CAKE S03', 'EVENT CAKE S01', 'EVENT CAKE S02', 'EVENT CAKE E18', 'EVENT CAKE E09', 'EVENT CAKE E28', 'EVENT CAKE E29', 'EVENT CAKE E27', 'EVENT CAKE E26', 'EVENT CAKE E19', 'EVENT CAKE E17', 'EVENT CAKE E10', 'EVENT CAKE E13', 'EVENT CAKE E16', 'EVENT CAKE E14', 'EVENT CAKE E15', 'EVENT CAKE E12', 'EVENT CAKE E11', 'EVENT CAKE E08', 'EVENT CAKE E07', 'EVENT CAKE E06', 'EVENT CAKE E05', 'EVENT CAKE E04', 'EVENT CAKE E03', 'EVENT CAKE E02', 'EVENT CAKE E01']

In [6]:
df["title_clean"] = df["title"]

df["title_clean"] = df["title_clean"].str.replace("APLLE", "APPLE", regex=False)
df["title_clean"] = df["title_clean"].str.replace("CRUNCCH", "CRUNCH", regex=False)

df[["title", "title_clean"]].head()

                title         title_clean
0  SET BACK TO BASICS  SET BACK TO BASICS
1     SET MINI CHICPO     SET MINI CHICPO
2      SET MINI BINGO      SET MINI BINGO
3      EVENT CAKE S07      EVENT CAKE S07
4      EVENT CAKE S06      EVENT CAKE S06

In [7]:
for i in range(5):
    print("Gốc:", df["title"].iloc[i])
    print("Clean:", df["title_clean"].iloc[i])
    print("---"*10)

Gốc: SET BACK TO BASICS
Clean: SET BACK TO BASICS
------------------------------
Gốc: SET MINI CHICPO
Clean: SET MINI CHICPO
------------------------------
Gốc: SET MINI BINGO
Clean: SET MINI BINGO
------------------------------
Gốc: EVENT CAKE S07
Clean: EVENT CAKE S07
------------------------------
Gốc: EVENT CAKE S06
Clean: EVENT CAKE S06
------------------------------

In [8]:
print(df["category"].value_counts())

category
Bánh Event sinh nhật    53
Bánh su Medium          26
Set bánh mini Chewy     17
Name: count, dtype: int64

In [9]:
import re

def categorize_title(title):
    if not isinstance(title, str):
        return "Không xác định"
    
    title = title.upper()

    if "EVENT CAKE" in title:
        return "Bánh Event sinh nhật"
    
    elif re.search(r"\bSET\b", title):
        return "Set bánh mini Chewy"
    
    else:
        return "Bánh su Medium"

In [10]:
df["category_new"] = df["title"].apply(categorize_title)

df[["title", "category", "category_new"]].head(10)

                title              category          category_new
0  SET BACK TO BASICS   Set bánh mini Chewy   Set bánh mini Chewy
1     SET MINI CHICPO   Set bánh mini Chewy   Set bánh mini Chewy
2      SET MINI BINGO   Set bánh mini Chewy   Set bánh mini Chewy
3      EVENT CAKE S07  Bánh Event sinh nhật  Bánh Event sinh nhật
4      EVENT CAKE S06  Bánh Event sinh nhật  Bánh Event sinh nhật
5      EVENT CAKE S05  Bánh Event sinh nhật  Bánh Event sinh nhật
6      EVENT CAKE S04  Bánh Event sinh nhật  Bánh Event sinh nhật
7   SET MINI GREENTEA   Set bánh mini Chewy   Set bánh mini Chewy
8      EVENT CAKE E46  Bánh Event sinh nhật  Bánh Event sinh nhật
9      EVENT CAKE E45  Bánh Event sinh nhật  Bánh Event sinh nhật

In [11]:
df["category_new"] = df["title"].apply(categorize_title)

In [12]:
# RAW TEXT -> VECTOR -> đưa vào ChromaDB
from sentence_transformers import SentenceTransformer
from typing import List

embedding_model = SentenceTransformer("keepitreal/vietnamese-sbert")

def get_embedding(text: str) -> List[float]:
    if not text or not text.strip():
        print("Empty text!")
        return []

    embedding = embedding_model.encode(text, normalize_embeddings=True)
    return embedding.tolist()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: keepitreal/vietnamese-sbert
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [14]:
df_chewy = df.copy()  # tạo bản sao để không làm thay đổi df gốc

df_chewy["category"] = df_chewy["category"].replace(
    "Bánh Event sinh nhật",
    "Bánh Event Sinh Nhật"
)

df_chewy.head(5)

,url,title,description,price,image_url,category,title_clean,category_new
0,https://chewychewy.vn/products/set-back-to-basics,SET BACK TO BASICS,Set 12 bánh với 4 loại nhân kem đặc biệt c...,149000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy,SET BACK TO BASICS,Set bánh mini Chewy
1,https://chewychewy.vn/products/set-mini-chicpo,SET MINI CHICPO,Set 12 bánh với sốt mayonaise được chế biế...,159000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy,SET MINI CHICPO,Set bánh mini Chewy
2,https://chewychewy.vn/products/set-mini-bingo,SET MINI BINGO,Set 12 bánh mix giữa 6 bánh nhân vanilla và...,179000 VND,http://product.hstatic.net/200000140863/produc...,Set bánh mini Chewy,SET MINI BINGO,Set bánh mini Chewy
3,https://chewychewy.vn/products/set-elegant,EVENT CAKE S07,"Set bánh bao gồm 20 bánh, nhân bánh vanill...",519000 VND,http://product.hstatic.net/200000140863/produc...,Bánh Event Sinh Nhật,EVENT CAKE S07,Bánh Event sinh nhật
4,https://chewychewy.vn/products/event-cake-s06-1,EVENT CAKE S06,* Lưu ý: Bánh sinh nhật thì Chewiers vui l...,429000 VND,http://product.hstatic.net/200000140863/produc...,Bánh Event Sinh Nhật,EVENT CAKE S06,Bánh Event sinh nhật

In [15]:
# DataFrame → text → embedding → ChromaDB
import re
import pandas as pd
import chromadb
from chromadb.utils import embedding_functions

# 1. Tạo embedding function

# Dùng model tiếng Việt để biến text -> vector
sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="keepitreal/vietnamese-sbert"
)

# 2. Khởi tạo ChromaDB client

# VECTOR_STORE là thư mục lưu dữ liệu vector xuống ổ cứng
client = chromadb.PersistentClient(path="VECTOR_STORE")

# Nếu muốn xóa dữ liệu cũ (tránh trùng) thì bỏ comment
client.delete_collection("chewy_chewy_aihi_01")
client.delete_collection("chewy_chewy_aihi_02")

# 3. Tạo collection (giống bảng trong DB)

# collection1: dùng title + description
collection1 = client.get_or_create_collection(
    name="chewy_chewy_aihi_01",
    embedding_function=sentence_transformer_ef
)

# collection2: dùng title + category
collection2 = client.get_or_create_collection(
    name="chewy_chewy_aihi_02",
    embedding_function=sentence_transformer_ef
)

# 4. Hàm tiền xử lý text

def preprocess_text(text: str) -> str:
    if pd.isna(text):
        return ""
    text = str(text).lower() # chuyển về chữ thường
    text = re.sub(r"[^\w\s,.]", "", text) # xóa ký tự đặc biệt
    text = re.sub(r"\s+", " ", text).strip() # xóa khoảng trắng thừa
    return text

# 5. Chuẩn hóa dữ liệu sản phẩm

def normalize_product(product: dict) -> dict:
    return {
        "url": "" if pd.isna(product.get("url")) else str(product.get("url")),
        "title": "" if pd.isna(product.get("title_clean")) else str(product.get("title_clean")),
        "description": "" if pd.isna(product.get("description")) else str(product.get("description")),
        "price": "" if pd.isna(product.get("price")) else str(product.get("price")),
        "image_url": "" if pd.isna(product.get("image_url")) else str(product.get("image_url")),
        "category": "" if pd.isna(product.get("category")) else str(product.get("category")),
    }

# 6. Thêm dữ liệu vào collection 1

# Dùng title + description (tìm kiếm theo nội dung)
def add_product_to_chromadb_01(product: dict, collection):
    product = normalize_product(product)

    combined_text = f"{product['title']} {product['description']}"
    combined_text = preprocess_text(combined_text)

    if not combined_text or not product["url"]:
        return

    collection.upsert( # dùng upsert để tránh lỗi trùng ID
        ids=[product["url"]],
        documents=[combined_text],
        metadatas=[{
            "url": product["url"],
            "title": product["title"],
            "description": product["description"],
            "price": product["price"],
            "image_url": product["image_url"],
            "category": product["category"]
        }]
    )

# 7. Thêm dữ liệu vào collection 2

# Dùng title + category (tìm kiếm theo loại)
def add_product_to_chromadb_02(product: dict, collection):
    product = normalize_product(product)

    combined_text = f"{product['title']} {product['category']}"
    combined_text = preprocess_text(combined_text)

    if not combined_text or not product["url"]:
        return

    collection.upsert(
        ids=[product["url"]],
        documents=[combined_text],
        metadatas=[{
            "url": product["url"],
            "title": product["title"],
            "description": product["description"],
            "price": product["price"],
            "image_url": product["image_url"],
            "category": product["category"]
        }]
    )

# 8. Đưa toàn bộ dữ liệu vào ChromaDB

for _, product in df_chewy.iterrows():
    add_product_to_chromadb_01(product.to_dict(), collection1)

for _, product in df_chewy.iterrows():
    add_product_to_chromadb_02(product.to_dict(), collection2)

print("Đã thêm dữ liệu vào ChromaDB thành công.")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: keepitreal/vietnamese-sbert
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Đã thêm dữ liệu vào ChromaDB thành công.

In [16]:
query = "bánh sinh nhật"

results = collection1.query(
    query_texts=[query],
    n_results=5
)

for i in range(len(results["documents"][0])):  
    print(f"Title: {results['metadatas'][0][i]['title']}")
    print(f"Description: {results['metadatas'][0][i]['description']}")
    print(f"Price: {results['metadatas'][0][i]['price']}")
    print(f"Image URL: {results['metadatas'][0][i]['image_url']}")
    print(f"URL: {results['metadatas'][0][i]['url']}")
    print(f"Category: {results['metadatas'][0][i]['category']}")
    print(f"Distance: {results['distances'][0][i]}")
    print("-" * 40)

Title: SET MINI CHOCOLATE
Description: Set 9 bánh mini nhân chocolate truyền thống ♥
Price: 99000 VND
Image URL: http://product.hstatic.net/200000140863/product/set_mini_chocolate__3dcdcfd97cdd4b2c8be226157528bab8_grande.png
URL: https://chewychewy.vn/products/mini-chocolate
Category: Set bánh mini Chewy
Distance: 0.4929240345954895
----------------------------------------
Title: CHEESE LOVER
Description: Bánh su medium nhân kem vanilla kèm topping phô mai kem béo ngậy
Price: 32000 VND
Image URL: http://product.hstatic.net/200000140863/product/cheese_lovver_f0605db955674bc08ab4c9e5a6112a92_grande.png
URL: https://chewychewy.vn/products/cheese-lover
Category: Bánh su Medium
Distance: 0.592300534248352
----------------------------------------
Title: SET MINI VANILLA
Description: Set 9 bánh mini nhân kem vanilla truyền thống ♥
Price: 89000 VND
Image URL: http://product.hstatic.net/200000140863/product/set_mini_vani_e6c0d6dfdfb9470bbf763d89772e2ab4_grande.png
URL: https://chewychewy.vn/products/mini-vanilla
Category: Set bánh mini Chewy
Distance: 0.6001486778259277
----------------------------------------
Title: CHEWY ORIGINAL
Description: Bánh su medium nhân vanilla truyền thống ♥
Price: 28000 VND
Image URL: http://product.hstatic.net/200000140863/product/chewy_original_840aa5a1886d4fbda2ccc6153bbdc9c2_grande.png
URL: https://chewychewy.vn/products/chewy-original
Category: Bánh su Medium
Distance: 0.6045825481414795
----------------------------------------
Title: CHEWY CHOCOLATE
Description: Bánh su medium nhân chocolate truyền thống ♥
Price: 28000 VND
Image URL: http://product.hstatic.net/200000140863/product/chewy_chocolate_1c72ab08a71e41f494e1da1488e40662_grande.png
URL: https://chewychewy.vn/products/chewy-chocolate
Category: Bánh su Medium
Distance: 0.6056041121482849
----------------------------------------

In [17]:
query = "tôi mua bánh sinh nhật"

results = collection2.query(
    query_texts=[query],
    n_results=5
)

print(results, "\n")

for i in range(len(results["documents"][0])):  
    print(f"Title: {results['metadatas'][0][i]['title']}")
    print(f"Description: {results['metadatas'][0][i]['description']}")
    print(f"Price: {results['metadatas'][0][i]['price']}")
    print(f"Image URL: {results['metadatas'][0][i]['image_url']}")
    print(f"Category: {results['metadatas'][0][i]['category']}")
    print(f"Distance: {results['distances'][0][i]}")
    print("-" * 40)

{'ids': [['https://chewychewy.vn/products/banh-event-mau-e09-1', 'https://chewychewy.vn/products/set-mini-crusty', 'https://chewychewy.vn/products/banh-event-mau-e03', 'https://chewychewy.vn/products/banh-event-mau-e01', 'https://chewychewy.vn/products/banh-event-mau-s01']], 'embeddings': None, 'documents': [['event cake e09 bánh event sinh nhật', 'set mini crusty set bánh mini chewy', 'event cake e03 bánh event sinh nhật', 'event cake e01 bánh event sinh nhật', 'event cake s01 bánh event sinh nhật']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'title': 'EVENT CAKE E09', 'description': '* Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥', 'category': 'Bánh Event Sinh Nhật', 'url': 'https://chewychewy.vn/products/banh-event-mau-e09-1', 'image_url': 'http://product.hstatic.net/200000140863/product/20_61dba315e1094f36b4598c6fa5adfe05_grande.png', 'price': '510000 VND'}, {'price': '119000 VND', 'url': 'https://chewychewy.vn/products/set-mini-crusty', 'image_url': 'http://product.hstatic.net/200000140863/product/set_mini_crusty__1a324c901b0347c6afa7bc818d387e46_grande.png', 'title': 'SET MINI CRUSTY', 'category': 'Set bánh mini Chewy', 'description': 'Set 9 bánh mini nhân chocolate kèm topping sốt socola đen và các loại bánh cốm ngũ cốc dinh dưỡng ♥'}, {'price': '425000 VND', 'url': 'https://chewychewy.vn/products/banh-event-mau-e03', 'category': 'Bánh Event Sinh Nhật', 'image_url': 'http://product.hstatic.net/200000140863/product/1_b2cf39acfdb14524a465160bc8f1aeaf_grande.png', 'title': 'EVENT CAKE E03', 'description': '* Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥'}, {'category': 'Bánh Event Sinh Nhật', 'image_url': 'http://product.hstatic.net/200000140863/product/e01-_25b_-_350k.jpg_2b47d24cc50e4f6fbc02fc2f2db1d592_grande.png', 'description': '* Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥', 'url': 'https://chewychewy.vn/products/banh-event-mau-e01', 'title': 'EVENT CAKE E01', 'price': '425000 VND'}, {'category': 'Bánh Event Sinh Nhật', 'price': '519000 VND', 'url': 'https://chewychewy.vn/products/banh-event-mau-s01', 'image_url': 'http://product.hstatic.net/200000140863/product/23_23262692717c4c33a9aa5d5982f953e8_grande.png', 'title': 'EVENT CAKE S01', 'description': '* Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥'}]], 'distances': [[0.3449551463127136, 0.34632062911987305, 0.34850192070007324, 0.34964799880981445, 0.3521016836166382]]}

Title: EVENT CAKE E09
Description: * Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥
Price: 510000 VND
Image URL: http://product.hstatic.net/200000140863/product/20_61dba315e1094f36b4598c6fa5adfe05_grande.png
Category: Bánh Event Sinh Nhật
Distance: 0.3449551463127136
----------------------------------------
Title: SET MINI CRUSTY
Description: Set 9 bánh mini nhân chocolate kèm topping sốt socola đen và các loại bánh cốm ngũ cốc dinh dưỡng ♥
Price: 119000 VND
Image URL: http://product.hstatic.net/200000140863/product/set_mini_crusty__1a324c901b0347c6afa7bc818d387e46_grande.png
Category: Set bánh mini Chewy
Distance: 0.34632062911987305
----------------------------------------
Title: EVENT CAKE E03
Description: * Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥
Price: 425000 VND
Image URL: http://product.hstatic.net/200000140863/product/1_b2cf39acfdb14524a465160bc8f1aeaf_grande.png
Category: Bánh Event Sinh Nhật
Distance: 0.34850192070007324
----------------------------------------
Title: EVENT CAKE E01
Description: * Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥
Price: 425000 VND
Image URL: http://product.hstatic.net/200000140863/product/e01-_25b_-_350k.jpg_2b47d24cc50e4f6fbc02fc2f2db1d592_grande.png
Category: Bánh Event Sinh Nhật
Distance: 0.34964799880981445
----------------------------------------
Title: EVENT CAKE S01
Description: * Lưu ý: Bánh sinh nhật thì Chewiers vui lòng đặt trước 2-3 tiếng giúp Chewy nhé ♥
Price: 519000 VND
Image URL: http://product.hstatic.net/200000140863/product/23_23262692717c4c33a9aa5d5982f953e8_grande.png
Category: Bánh Event Sinh Nhật
Distance: 0.3521016836166382
----------------------------------------

In [18]:
def weighted_reciprocal_rank(doc_lists, weights=None, c=60):
    """
    Gộp nhiều danh sách kết quả bằng Weighted Reciprocal Rank Fusion (RRF).

    Args:
        doc_lists: List các danh sách document.
        weights: Trọng số cho từng danh sách. Nếu None thì mọi danh sách có weight = 1.
        c: Hằng số trong công thức RRF.

    Returns:
        List document đã được sắp xếp theo điểm RRF giảm dần.
    """
    if weights is None:
        weights = [1] * len(doc_lists)

    if len(doc_lists) != len(weights):
        raise ValueError("Số lượng doc_lists phải bằng số lượng weights.")

    rrf_score_dict = {}
    doc_map = {}

    for doc_list, weight in zip(doc_lists, weights):
        for rank, doc in enumerate(doc_list, start=1):
            doc_id = doc["_id"]
            score = weight * (1 / (rank + c))

            if doc_id not in rrf_score_dict:
                rrf_score_dict[doc_id] = 0.0
                doc_map[doc_id] = doc

            rrf_score_dict[doc_id] += score

    sorted_doc_ids = sorted(
        rrf_score_dict.keys(),
        key=lambda x: rrf_score_dict[x],
        reverse=True
    )

    return [doc_map[doc_id] for doc_id in sorted_doc_ids]


def parse_chroma_results(results):
    """
    Chuyển kết quả từ ChromaDB thành list dict dễ xử lý hơn.
    """
    parsed = []

    if not results["ids"] or not results["ids"][0]:
        return parsed

    for i in range(len(results["ids"][0])):
        parsed.append({
            "_id": results["ids"][0][i],
            "url": results["metadatas"][0][i].get("url", ""),
            "title": results["metadatas"][0][i].get("title", ""),
            "description": results["metadatas"][0][i].get("description", ""),
            "price": results["metadatas"][0][i].get("price", ""),
            "image_url": results["metadatas"][0][i].get("image_url", ""),
            "category": results["metadatas"][0][i].get("category", ""),
            "distance": results["distances"][0][i] if "distances" in results else None
        })

    return parsed


def hybrid_search(query: str, collection, limit=10):
    """
    Hybrid search bằng 2 lượt truy vấn:
    1. Query gốc
    2. Query đã preprocess

    Sau đó gộp kết quả bằng RRF.
    """
    if not query or not query.strip():
        return []

    clean_query = preprocess_text(query)

    results_1 = collection.query(
        query_texts=[query],
        n_results=limit
    )

    results_2 = collection.query(
        query_texts=[clean_query],
        n_results=limit
    )

    parsed_results_1 = parse_chroma_results(results_1)
    parsed_results_2 = parse_chroma_results(results_2)

    fused_documents = weighted_reciprocal_rank(
        doc_lists=[parsed_results_1, parsed_results_2],
        weights=[1, 1]
    )

    return fused_documents[:limit]


def enhance_prompt(query: str, collection, limit=10):
    """
    Tạo context/prompt từ kết quả hybrid search.
    """
    knowledge = hybrid_search(query, collection, limit)

    if not knowledge:
        return "Không tìm thấy sản phẩm phù hợp."

    enhanced_prompt = ""
    for i, result in enumerate(knowledge, start=1):
        enhanced_prompt += (
            f"[Sản phẩm {i}]\n"
            f"Title: {result.get('title', 'N/A')}\n"
            f"Description: {result.get('description', 'N/A')}\n"
            f"Price: {result.get('price', 'N/A')}\n"
            f"Image URL: {result.get('image_url', 'N/A')}\n"
            f"URL: {result.get('url', 'N/A')}\n"
            f"Category: {result.get('category', 'N/A')}\n\n"
        )

    return enhanced_prompt

In [19]:
def display_result(results: list):
    if not results:
        print("Không có kết quả.")
        return

    for i, product in enumerate(results, start=1):
        print(f"[Sản phẩm {i}]")
        print("Tên:", product.get("title", "N/A"))
        print("Giá:", product.get("price", "N/A"))
        print("Mô tả:", product.get("description", "N/A"))
        print("Hình ảnh:", product.get("image_url", "N/A"))
        print("Danh mục:", product.get("category", "N/A"))
        print("Link:", product.get("url", "N/A"))
        print("-" * 40)

In [20]:
results = hybrid_search("bánh sinh nhật", collection1)
display_result(results)

[Sản phẩm 1]
Tên: SET MINI CHOCOLATE
Giá: 99000 VND
Mô tả: Set 9 bánh mini nhân chocolate truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_chocolate__3dcdcfd97cdd4b2c8be226157528bab8_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-chocolate
----------------------------------------
[Sản phẩm 2]
Tên: CHEESE LOVER
Giá: 32000 VND
Mô tả: Bánh su medium nhân kem vanilla kèm topping phô mai kem béo ngậy
Hình ảnh: http://product.hstatic.net/200000140863/product/cheese_lovver_f0605db955674bc08ab4c9e5a6112a92_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/cheese-lover
----------------------------------------
[Sản phẩm 3]
Tên: SET MINI VANILLA
Giá: 89000 VND
Mô tả: Set 9 bánh mini nhân kem vanilla truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_vani_e6c0d6dfdfb9470bbf763d89772e2ab4_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-vanilla
----------------------------------------
[Sản phẩm 4]
Tên: CHEWY ORIGINAL
Giá: 28000 VND
Mô tả: Bánh su medium nhân vanilla truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/chewy_original_840aa5a1886d4fbda2ccc6153bbdc9c2_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/chewy-original
----------------------------------------
[Sản phẩm 5]
Tên: CHEWY CHOCOLATE
Giá: 28000 VND
Mô tả: Bánh su medium nhân chocolate truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/chewy_chocolate_1c72ab08a71e41f494e1da1488e40662_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/chewy-chocolate
----------------------------------------
[Sản phẩm 6]
Tên: GREEN TEA
Giá: 35000 VND
Mô tả: Bánh su medium nhân trà xanh kèm topping socola trắng và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/green_tea_e86d17a4dbb241e28343b9b4dfa4d9ca_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/green-tea
----------------------------------------
[Sản phẩm 7]
Tên: ALMOND SWEETHEART
Giá: 32000 VND
Mô tả: Bánh su medium nhân vanilla kèm topping socola trắng và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/almond_sweetheart_fa1c4ed296624be5917ac7d002498caf_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/almond-sweetheart
----------------------------------------
[Sản phẩm 8]
Tên: EVENT CAKE S02
Giá: 519000 VND
Mô tả: Set gồm 25 bánh mini nhân kem vanilla ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/22_dafccd766db84283b3325f445244ed5c_grande.png
Danh mục: Bánh Event Sinh Nhật
Link: https://chewychewy.vn/products/banh-event-mau-s02
----------------------------------------
[Sản phẩm 9]
Tên: APPLE CHEESE
Giá: 32000 VND
Mô tả: Bánh su medium nhân kem vanilla kèm topping phô mai kem mứt táo ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/apple_cheese_386d0b04ee4948e1b30f3f5227b24e0c_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/apple-cheese
----------------------------------------
[Sản phẩm 10]
Tên: STRAWBERRY CHEESE
Giá: 28000 VND
Mô tả: Bánh su medium nhân kem vanilla kèm topping phô mai kem mứt dâu ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/strawberry_cheese_ab925b41a225410bbf3d737e7f86149a_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/strawberry-cheese
----------------------------------------

In [85]:
results = hybrid_search("bánh mini socola", collection1)
display_result(results)

[Sản phẩm 1]
Tên: SET MINI CHOCOLATE
Giá: 99000 VND
Mô tả: Set 9 bánh mini nhân chocolate truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_chocolate__3dcdcfd97cdd4b2c8be226157528bab8_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-chocolate
----------------------------------------
[Sản phẩm 2]
Tên: CHEWY CHOCOLATE
Giá: 28000 VND
Mô tả: Bánh su medium nhân chocolate truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/chewy_chocolate_1c72ab08a71e41f494e1da1488e40662_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/chewy-chocolate
----------------------------------------
[Sản phẩm 3]
Tên: CHOCOLATE OREO CRUNCH
Giá: 32000 VND
Mô tả: Bánh su medium nhân chocolate kèm theo topping sốt socola và bánh oreo nghiền nhuyễn
Hình ảnh: http://product.hstatic.net/200000140863/product/chocolate_oreo_crunch_76b54c8b139842a0b0812f8600494a3f_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/chocolate-oreo-crunch
----------------------------------------
[Sản phẩm 4]
Tên: CHEESE LOVER
Giá: 32000 VND
Mô tả: Bánh su medium nhân kem vanilla kèm topping phô mai kem béo ngậy
Hình ảnh: http://product.hstatic.net/200000140863/product/cheese_lovver_f0605db955674bc08ab4c9e5a6112a92_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/cheese-lover
----------------------------------------
[Sản phẩm 5]
Tên: SET MINI HAPPY
Giá: 139000 VND
Mô tả: Set 12 bánh nhân chocolate thơm ngon, hòa thêm một chút vị đắng nhẹ đặc trưng của socola kèm theo những topping hạnh nhân, oreo nghiền nhuyễn, sốt socola và bánh cốm ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_happy_32bfda8262344bde89cae7d283d0d93a_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-happy
----------------------------------------
[Sản phẩm 6]
Tên: ALMOND SWEETHEART
Giá: 32000 VND
Mô tả: Bánh su medium nhân vanilla kèm topping socola trắng và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/almond_sweetheart_fa1c4ed296624be5917ac7d002498caf_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/almond-sweetheart
----------------------------------------
[Sản phẩm 7]
Tên: GREEN TEA
Giá: 35000 VND
Mô tả: Bánh su medium nhân trà xanh kèm topping socola trắng và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/green_tea_e86d17a4dbb241e28343b9b4dfa4d9ca_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/green-tea
----------------------------------------
[Sản phẩm 8]
Tên: SET MINI GREENTEA
Giá: 119000 VND
Mô tả: Set 9 bánh với nhân kem trà xanh thơm lừng, ngọt dịu kèm thêm vị đắng nhẹ của nhà Chewy Chewy ♥Topping phía trên gồm sốt socola trắng và hạnh nhân rang thơm ơi là thơm ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_green_tea_79d64e7060774e2bae2870f635754108_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/set-mini-greentea
----------------------------------------
[Sản phẩm 9]
Tên: ALMOND CHOCOLATE CRUNCH
Giá: 35000 VND
Mô tả: Bánh su medium nhân chocolate kèm topping socola đen và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/almond_chocolate_crunch_42cb52736253440fa15163758ed25967_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/almond-chocolate-crunch
----------------------------------------
[Sản phẩm 10]
Tên: SET MINI VANILLA
Giá: 89000 VND
Mô tả: Set 9 bánh mini nhân kem vanilla truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_vani_e6c0d6dfdfb9470bbf763d89772e2ab4_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-vanilla
----------------------------------------

In [21]:
results = hybrid_search("tôi muốn mua bánh sinh nhật cho bạn gái", collection1)
display_result(results)

[Sản phẩm 1]
Tên: SET MINI CHOCOLATE
Giá: 99000 VND
Mô tả: Set 9 bánh mini nhân chocolate truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_chocolate__3dcdcfd97cdd4b2c8be226157528bab8_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-chocolate
----------------------------------------
[Sản phẩm 2]
Tên: EVENT CAKE S02
Giá: 519000 VND
Mô tả: Set gồm 25 bánh mini nhân kem vanilla ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/22_dafccd766db84283b3325f445244ed5c_grande.png
Danh mục: Bánh Event Sinh Nhật
Link: https://chewychewy.vn/products/banh-event-mau-s02
----------------------------------------
[Sản phẩm 3]
Tên: ALMOND SWEETHEART
Giá: 32000 VND
Mô tả: Bánh su medium nhân vanilla kèm topping socola trắng và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/almond_sweetheart_fa1c4ed296624be5917ac7d002498caf_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/almond-sweetheart
----------------------------------------
[Sản phẩm 4]
Tên: CHEWY ORIGINAL
Giá: 28000 VND
Mô tả: Bánh su medium nhân vanilla truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/chewy_original_840aa5a1886d4fbda2ccc6153bbdc9c2_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/chewy-original
----------------------------------------
[Sản phẩm 5]
Tên: CHEESE LOVER
Giá: 32000 VND
Mô tả: Bánh su medium nhân kem vanilla kèm topping phô mai kem béo ngậy
Hình ảnh: http://product.hstatic.net/200000140863/product/cheese_lovver_f0605db955674bc08ab4c9e5a6112a92_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/cheese-lover
----------------------------------------
[Sản phẩm 6]
Tên: SET MINI VANILLA
Giá: 89000 VND
Mô tả: Set 9 bánh mini nhân kem vanilla truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_vani_e6c0d6dfdfb9470bbf763d89772e2ab4_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-vanilla
----------------------------------------
[Sản phẩm 7]
Tên: CHEWY CHOCOLATE
Giá: 28000 VND
Mô tả: Bánh su medium nhân chocolate truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/chewy_chocolate_1c72ab08a71e41f494e1da1488e40662_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/chewy-chocolate
----------------------------------------
[Sản phẩm 8]
Tên: GREEN TEA
Giá: 35000 VND
Mô tả: Bánh su medium nhân trà xanh kèm topping socola trắng và phủ một lớp hạnh nhân rang thơm lừng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/green_tea_e86d17a4dbb241e28343b9b4dfa4d9ca_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/green-tea
----------------------------------------
[Sản phẩm 9]
Tên: STRAWBERRY CHEESE
Giá: 28000 VND
Mô tả: Bánh su medium nhân kem vanilla kèm topping phô mai kem mứt dâu ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/strawberry_cheese_ab925b41a225410bbf3d737e7f86149a_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/strawberry-cheese
----------------------------------------
[Sản phẩm 10]
Tên: STRAWBERRY COTTON YOGURT
Giá: 32000 VND
Mô tả: Bánh su medium nhân yogurt kèm topping mứt dâu đỏ au ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/strawberry_cotton_yogurt_d97e8e46311149c7b91c6f41caa1e150_grande.png
Danh mục: Bánh su Medium
Link: https://chewychewy.vn/products/strawberry-cotton-yogurt
----------------------------------------

In [22]:
results = hybrid_search("set bánh", collection2)
display_result(results)

[Sản phẩm 1]
Tên: SET MINI CRUSTY
Giá: 119000 VND
Mô tả: Set 9 bánh mini nhân chocolate kèm topping sốt socola đen và các loại bánh cốm ngũ cốc dinh dưỡng ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_crusty__1a324c901b0347c6afa7bc818d387e46_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/set-mini-crusty
----------------------------------------
[Sản phẩm 2]
Tên: SET MINI LUXURY
Giá: 179000 VND
Mô tả: Set 12 bánh mix giữa 6 bánh nhân vanilla và 6 bánh nhân chocolate thơm ngon tròn vị.Topping bao gồm mứt chanh, phô mai kem kèm theo mứt dâu, sốt socola phủ hạt choco triple và bánh cốm ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_luxury_5e35c50dde3f44e195f1b6d48b5f67d7_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-luxury
----------------------------------------
[Sản phẩm 3]
Tên: SET BACK TO BASICS
Giá: 149000 VND
Mô tả: Set 12 bánh với 4 loại nhân kem đặc biệt của Chewy Chewy
Hình ảnh: http://product.hstatic.net/200000140863/product/set_back_to_basics_c97d469ec45e4b26a592f0b1b4899539_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/set-back-to-basics
----------------------------------------
[Sản phẩm 4]
Tên: SET MINI CHICPO
Giá: 159000 VND
Mô tả: Set 12 bánh với sốt mayonaise được chế biến theo công thức đặc biệt, topping 6 chà bông gà, 6 chà bông heo ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_chicpo_8acd8d0496554b519da0df1a9d8faa53_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/set-mini-chicpo
----------------------------------------
[Sản phẩm 5]
Tên: SET MINI BINGO
Giá: 179000 VND
Mô tả: Set 12 bánh mix giữa 6 bánh nhân vanilla và 6 bánh nhân chocolate thơm ngon tròn vị.Topping creamcheese kèm mứt cam, phô mai sợi mứt dâu, socola và lớp ngũ cốc ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_bingo_fa3a35ea173d47bfa65423e874cd85a6_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/set-mini-bingo
----------------------------------------
[Sản phẩm 6]
Tên: SET MINI DORAEMON
Giá: 129000 VND
Mô tả: Set 12 bánh su mini kem vanilla thơm béo, kèm theo topping các loại mứt trái cây: dâu, cam, táo và việt quất.
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_doraemon_0f5c9d98c7c5479a8e66ce00f299234c_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-doraemon
----------------------------------------
[Sản phẩm 7]
Tên: SET MINI YOGURT
Giá: 119000 VND
Mô tả: Set mini 9 bánh nhân yogurt đặc biệt chỉ có tại Chewy Chewy ♥ Topping gồm các loại mứt: Táo, Dâu, Việt Quất và Cam
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_yogurt__f58f0c7c2d3e4ce4984242fa9002cb6e_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-yogurt
----------------------------------------
[Sản phẩm 8]
Tên: SET MINI VANILLA
Giá: 89000 VND
Mô tả: Set 9 bánh mini nhân kem vanilla truyền thống ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_vani_e6c0d6dfdfb9470bbf763d89772e2ab4_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-vanilla
----------------------------------------
[Sản phẩm 9]
Tên: SET MINI HAPPY
Giá: 139000 VND
Mô tả: Set 12 bánh nhân chocolate thơm ngon, hòa thêm một chút vị đắng nhẹ đặc trưng của socola kèm theo những topping hạnh nhân, oreo nghiền nhuyễn, sốt socola và bánh cốm ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/set_mini_happy_32bfda8262344bde89cae7d283d0d93a_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/mini-happy
----------------------------------------
[Sản phẩm 10]
Tên: SET MINI BƠ TỎI
Giá: 119000 VND
Mô tả: Set Mini Chewy Bơ tỏi 9 bánh đặc biệt nhà Chewy Chewy ♥
Hình ảnh: http://product.hstatic.net/200000140863/product/9banh_555c1891ffe744aa95da90de6b7bd371_grande.png
Danh mục: Set bánh mini Chewy
Link: https://chewychewy.vn/products/set-mini-chewy-bo-toi-9-banh
----------------------------------------